# Generated by Django 2.2.1 on 2019-06-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pdf',
            field=models.FileField(default='default.txt', upload_to='documents/'),
        ),
    ]
